apiVersion: v1
kind: Service
metadata:
  name: smart-lock-api
  labels:
    app: smart-lock-api
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30080 # 30000-32767の範囲で指定
      protocol: TCP
      name: http
  selector:
    app: smart-lock-api
