apiVersion: v1
kind: Service
metadata:
  name: smart-lock-api
  labels:
    app: smart-lock-api
spec:
  type: ClusterIP # LoadBalancerやNodePortに変更可能
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: smart-lock-api
